/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package board.games;

import board.games.hello.HelloServlet;
import org.eclipse.jetty.server.Connector;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.servlet.ServletHandler;

public class App {

    public static void main(String[] args) throws Exception {
        System.out.println("Starting Board Games...");

        Server server = new Server();
        ServerConnector connector = new ServerConnector(server);
        connector.setPort(8080);
        server.setConnectors(new Connector[] {connector});

        ServletHandler servletHandler = new ServletHandler();
        server.setHandler(servletHandler);

        servletHandler.addServletWithMapping(HelloServlet.class, "/hello");

        server.start();
    }
}
